import { Book } from "../interfaces/interfaces";

export const asideLinks = [
  { text: "Inicio", href: "/" },
  { text: "Libros", href: "/books" },
  { text: "Mis Alquileres", href: "/rentals" },
  { text: "Buscar", href: "/search" },
  { text: "Contacto", href: "/contact" },
];

export const exampleBook: Book = {
  id: 43333,
  title: "Cien años de soledad",
  author: "Gabriel García Márquez",
  publicationYear: 1967,
  isbn10: "1234567890",
  isbn13: "123-4567890123",
  coverImage:
    "https://m.media-amazon.com/images/I/71YoFJSz3LL._AC_UF1000,1000_QL80_.jpg",
  synopsis: "Esta es una sinopsis del libro.",
  reviews: "Reseñas del libro.",
};

export const appBooks: Book[] = [
  {
    id: 1,
    title: "El amor en los tiempos del cólera",
    author: "Gabriel García Márquez",
    publicationYear: 1985,
    isbn10: "1234567891",
    isbn13: "123-4567890124",
    coverImage: "https://m.media-amazon.com/images/I/81YPlYG-b9L._AC_UF894,1000_QL80_.jpg",
    synopsis: "Una historia de amor que perdura a lo largo de los años en un pequeño pueblo caribeño.",
    reviews: "Una obra maestra que explora los temas del amor y la perseverancia.",
  },
  {
    id: 2,
    title: "El psicoanalista",
    author: "John Katzenbach",
    publicationYear: 2002,
    isbn10: "1234567892",
    isbn13: "123-4567890125",
    coverImage: "https://m.media-amazon.com/images/I/91-ELvEEeIL._AC_UF894,1000_QL80_.jpg",
    synopsis: "Un thriller psicológico donde un psicoanalista debe descifrar una amenaza para salvar su vida.",
    reviews: "Un libro lleno de suspenso y giros inesperados que te mantendrá al borde del asiento.",
  },
  {
    id: 3,
    title: "Muchos maestros, muchas vidas",
    author: "Brian Weiss",
    publicationYear: 1988,
    isbn10: "1234567893",
    isbn13: "123-4567890126",
    coverImage: "https://m.media-amazon.com/images/I/71SAdFFD04L._AC_UF1000,1000_QL80_.jpg",
    synopsis: "Un viaje espiritual a través de vidas pasadas que ofrece enseñanzas profundas sobre la existencia.",
    reviews: "Una lectura inspiradora que invita a la reflexión sobre el alma y su evolución.",
  },
  {
    id: 4,
    title: "Distancia de rescate",
    author: "Samanta Schweblin",
    publicationYear: 2014,
    isbn10: "1234567894",
    isbn13: "123-4567890127",
    coverImage: "https://m.media-amazon.com/images/I/918wQLTNgVL._AC_UF894,1000_QL80_.jpg",
    synopsis: "Una novela inquietante sobre la maternidad, el miedo y la fragilidad de la vida.",
    reviews: "Un relato perturbador y cautivador que explora los límites del amor y la protección.",
  },
  {
    id: 5,
    title: "El pez dorado",
    author: "J.M.G. Le Clézio",
    publicationYear: 1982,
    isbn10: "1234567895",
    isbn13: "123-4567890128",
    coverImage: "https://m.media-amazon.com/images/I/81xzGJK6RGL._AC_UF1000,1000_QL80_.jpg",
    synopsis: "La travesía de una joven que busca su identidad y libertad a través de diferentes culturas.",
    reviews: "Una narrativa rica en detalles que destaca la resiliencia y el espíritu humano.",
  },
  {
    id: 6,
    title: "Perdimos en el fuego",
    author: "Mariana Enríquez",
    publicationYear: 2016,
    isbn10: "1234567896",
    isbn13: "123-4567890129",
    coverImage: "https://m.media-amazon.com/images/I/41Fk3o99nsL.jpg",
    synopsis: "Una colección de cuentos oscuros que exploran la violencia y el horror en la vida cotidiana.",
    reviews: "Historias intensas y perturbadoras que no dejarán indiferente al lector.",
  },
  {
    id: 7,
    title: "Papillon",
    author: "Henri Charrière",
    publicationYear: 1969,
    isbn10: "1234567897",
    isbn13: "123-4567890130",
    coverImage: "https://m.media-amazon.com/images/I/815FoLzxfvL._AC_UF894,1000_QL80_.jpg",
    synopsis: "La autobiografía de un hombre injustamente encarcelado que lucha por su libertad.",
    reviews: "Un relato de supervivencia y determinación que inspira y conmueve.",
  },
  {
    id: 8,
    title: "La Malinche",
    author: "Laura Esquivel",
    publicationYear: 2006,
    isbn10: "1234567898",
    isbn13: "123-4567890131",
    coverImage: "https://m.media-amazon.com/images/I/71UvewhRptL._AC_UF894,1000_QL80_.jpg",
    synopsis: "La vida de La Malinche, una mujer clave en la historia de México, contada con maestría.",
    reviews: "Una novela histórica fascinante que da voz a una figura controvertida y fundamental.",
  },
  {
    id: 9,
    title: "Como agua para chocolate",
    author: "Laura Esquivel",
    publicationYear: 1989,
    isbn10: "1234567899",
    isbn13: "123-4567890132",
    coverImage: "https://m.media-amazon.com/images/I/71vbGbBzlZL._AC_UF1000,1000_QL80_.jpg",
    synopsis: "Una novela de amor y cocina donde las recetas culinarias se entrelazan con las emociones.",
    reviews: "Un clásico que combina magia, romance y gastronomía en una narrativa única.",
  },
];

